//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class activ
    {
        public int ID_activ { get; set; }
        public Nullable<double> C_ { get; set; }
        public string Наименование_мероприятия { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<double> Дни { get; set; }
        public string Активность { get; set; }
        public Nullable<double> День { get; set; }
        public Nullable<System.DateTime> Время_начала { get; set; }
        public string Модератор { get; set; }
        public string Жюри_1 { get; set; }
        public string Жюри_2 { get; set; }
        public string Жюри_3 { get; set; }
        public string Жюри_4 { get; set; }
        public string Жюри_5 { get; set; }
        public string Победитель { get; set; }
        public string C_1 { get; set; }
    }
}
