//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class meet
    {
        public int C_ { get; set; }
        public string Событие { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> DAYS { get; set; }
        public Nullable<double> Город { get; set; }
    }
}
