//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrMeetingEntities1 : DbContext
    {
        private static RegistrMeetingEntities1 _context;
        public RegistrMeetingEntities1()
            : base("name=RegistrMeetingEntities1")
        {
        }
    
        public static RegistrMeetingEntities1 getContext()
        {
            if (_context == null)
            {
                _context = new RegistrMeetingEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activ> activ { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<juri> juri { get; set; }
        public virtual DbSet<meet> meet { get; set; }
        public virtual DbSet<moder> moder { get; set; }
        public virtual DbSet<organizator> organizator { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
