//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int ID_student { get; set; }
        public string ФИО { get; set; }
        public string Почта { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public Nullable<double> страна { get; set; }
        public Nullable<double> телефон { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public string пол { get; set; }
    }
}
